### ISSUE TITLE
Add Sloan's post "An app can be a home-cooked meal" to catalog

### ISSUE THREAD

**Issue by jryans** [malleable-systems/malleable.systems#10]
https://www.robinsloan.com/notes/home-cooked-app/

**Comment by akkartik** [comment]
I'm trying to work on this one, and I wish I had a space to add the following note:

> Related to "situated software": https://buttondown.email/hillelwayne/archive/situated-software; https://www.gwern.net/docs/technology/2004-03-30-shirky-situatedsoftware.html

**Comment by jryans** [comment]
For now, you could add that info in the free-form `description` field, which accepts Markdown for styled text. If we later end up with lots of "related to" data, we can reorganise it into something more structured.
