### ISSUE TITLE
Add Matuschak's "Armories for tool-maker / tool-user collaborations" to catalog

### ISSUE THREAD

**Issue by jryans** [malleable-systems/malleable.systems#53]
https://www.patreon.com/posts/armories-for-52549432

"...certain kinds of progress in “tools for thought” may depend on figuring out a way for “tool-makers” to work very closely with “tool-users”—people who are in some sense devoting their lives to playing the instruments we create. This goes beyond the typical lite-ethnographic “design research” practiced by firms like IDEO: luthiers must become at least modest violinists themselves, embedded in those communities, and capable of making original (but probably limited) contributions to their problems. Likewise, the tool-users must become active participants in the design project, learning enough about how the tool is built to contribute meaningful ideas."

"The pair must proactively develop an armory of tool ideas (both embryonic and mature) to equip the tool-user’s explorations."

Suggester: me

**Comment by jryans** [comment]
This post has been [unlocked](https://twitter.com/andy_matuschak/status/1455265645835153411), so it's now accessible to all.

**Comment by akkartik** [comment]
I think I'll summarize this next if you haven't already started.

**Comment by jryans** [comment]
Sounds great, please go ahead! 😄
